#include "config.h"

namespace text {

    std::map<std::string, word> config_m{
        {"zero",      word{order::units, 0}},
        {"one",       word{order::units, 1}},
        {"two",       word{order::units, 2}},
        {"three",     word{order::units, 3}},
        {"four",      word{order::units, 4}},
        {"five",      word{order::units, 5}},
        {"six",       word{order::units, 6}},
        {"seven",     word{order::units, 7}},
        {"eight",     word{order::units, 8}},
        {"nine",      word{order::units, 9}},
        {"ten",       word{order::units, 10}},
        {"eleven",    word{order::units, 11}},
        {"twelve",    word{order::units, 12}},
        {"thirteen",  word{order::units, 13}},
        {"fourteen",  word{order::units, 14}},
        {"fifteen",   word{order::units, 15}},
        {"sixteen",   word{order::units, 16}},
        {"seventeen", word{order::units, 17}},
        {"eighteen",  word{order::units, 18}},
        {"nineteen",  word{order::units, 19}},
        {"twenty",    word{order::tens, 2}},
        {"thirty",    word{order::tens, 3}},
        {"forty",     word{order::tens, 4}},
        {"fifty",     word{order::tens, 5}},
        {"sixty",     word{order::tens, 6}},
        {"seventy",   word{order::tens, 7}},
        {"eighty",    word{order::tens, 8}},
        {"ninety",    word{order::tens, 9}},
        {"hundred",   word{order::hundreds, 1}},
        {"thousand",  word{order::thousands, 1}},
        {"million",   word{order::millions, 1}},
        {"billion",  word{order::billions, 1}}
    };

    std::set<std::string> set_of_number_words{
        "zero",
        "one",
        "two",
        "three",
        "four",
        "five",
        "six",
        "seven",
        "eight",
        "nine",
        "ten",
        "eleven",
        "twelve",
        "thirteen",
        "fourteen",
        "fifteen",
        "sixteen",
        "seventeen",
        "eighteen",
        "nineteen",
        "twenty",
        "thirty",
        "forty",
        "fifty",
        "sixty",
        "seventy",
        "eighty",
        "ninety",
        "hundred",
        "thousand",
        "million",
        "billion"
    };

}// namespace text